

server:
  port: 8888
  
spring:
  cloud:
      config:
          server:
              git:
                uri: https://github.com/daniprimo/microservices-repo
                search-paths: fornecedor
